server:
  port: 10086
spring:
  application:
    name: leyou-registry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
    register-with-eureka: false #是否把自己注册到eureka
    fetch-registry: false  #是否拉去eureka服务列表
  server:
    enable-self-preservation: false  #关闭自我保护模式
    delta-retention-timer-interval-in-ms: 5000  #没隔5秒钟，进行一次服务列表的清理